### ISSUE TITLE
enlace roto

### ISSUE THREAD

**Issue by AntonioDiaz** [Fictizia/Curso-Node.js-para-desarrolladores-Front-end_ed5#1]
Hola, parece que el enlace a la imagen del logo de node.js está roto (http://www.fictizia.com/assets/styles/styleImgs/wideBox/widebox_js.png).
Se utiliza en el README.md principal y el de la clase1.

salu2

**Comment by ancoar** [comment]
Hola Antonio, soy Ángel, responsable del área de Desarrollo interactivo y Web de Fictizia.
Hemos cambiado completamente fictizia.com y parece que las imágenes de cabecera de los repos en GitHub se han marchado del host con la versión anterior del site así que… ¿parece un buen momento para renovarlas verdad? jeje Ya estamos en ello ;)

¡¡Gracias por el aviso!!

**Comment by josex2r** [comment]
Gracias por avisar y por arreglarlo ^^
Cierro la issue.
